name: Build

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: psdk_ros2
      - uses: actions/checkout@v4
        with:
          repository: dji-sdk/Payload-SDK
          ref: 3.8
          path: Payload-SDK
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble
          ROS_REPO: main
          ADDITIONAL_DEBS: libopus-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libusb-1.0-0-dev
          TARGET_WORKSPACE: '. -Payload-SDK/CMakeLists.txt -Payload-SDK/samples/sample_c/platform -Payload-SDK/samples/sample_c++/platform/linux/manifold2/CMakeLists.txt -Payload-SDK/samples/sample_c++/platform/linux/nvidia_jetson'
          NOT_TEST_BUILD: true
          # UPSTREAM_WORKSPACE: github:dji-sdk/Payload-SDK#3.8